
# VMWare inventory collector configuration
# Enter the information for vCenter login account and target vm
# 
# example:
#
# url = "https://192.168.10.100/sdk"  # vCenter IP or URL
# user = "test_user"
# password = "P@ssword"
# server = "w2016"                    # vm name

url = "https://192.168.0.200/sdk"
user = "root"
password = "goliath19a$"
server = "centos80"

# The following parameters are optional

# List of monitored servers other than the local server
#
# example:
#
# servers = ["host1", "host2"]

# Additional metrics list of VMWare vSphere Managed Object API. 
#
# Notice: 
#   The results of all added metrics are saved in the "all.json".
#
# Reference : 
#   https://code.vmware.com/apis/968/vsphere
# 
# [[metrics]]
# 
# id = "config"   # unique key
# level = 0       # command level [0-2]
# text = "config" # Managed Object Description

# The following commented out metrics are set by default

# [[metrics]]
# 
# id = "summary"
# level = 0
# text = "summary"
# 
# [[metrics]]
# 
# id = "resourceConfig"
# level = 0
# text = "resourceConfig"
# 
# [[metrics]]
# 
# id = "guestHeartbeatStatus"
# level = 0
# text = "guestHeartbeatStatus"
# 
# [[metrics]]
# 
# id = "config"
# level = 0
# text = "config"
# 
# [[metrics]]
# 
# id = "guest"
# level = 0
# text = "guest"
